### 获取所有服务实例84
GET http://localhost:8484/findAll?service=com.yuanstack.xrpc.UserService

### 注册一个实例
POST http://localhost:8484/register?service=com.yuanstack.xrpc.UserService
Content-Type: application/json

{
  "context": "xrpc",
  "host": "127.0.0.1",
  "port": 8084,
  "scheme": "http",
  "status": false,
  "parameters": {
    "env": "dev",
    "tag": "RED"
  }
}

### 取消注册一个实例
POST http://localhost:8484/unregister?service=com.yuanstack.xrpc.UserService
Content-Type: application/json

{
  "context": "xrpc",
  "host": "127.0.0.1",
  "port": 8081,
  "scheme": "http"
}

### renew一个实例8081
POST http://localhost:8484/renew?service=com.yuanstack.xrpc.UserService
Content-Type: application/json

{
  "context": "xrpc",
  "host": "127.0.0.1",
  "port": 8081,
  "scheme": "http"
}

### 获取服务的版本
POST http://localhost:8484/version?service=com.yuanstack.xrpc.UserService

### info
GET http://localhost:8484/info
### cluster
GET http://localhost:8484/cluster
### info 85
GET http://localhost:8485/info
### cluster 85
GET http://localhost:8485/cluster
### sl 85
GET http://localhost:8485/sl

### snapshot 8484
GET http://localhost:8484/snapshot